services:
  ppt_app:
    image: ppt_app_image
    container_name: ppt_app_container
    build: .
    ports:
      - "8085:80"
    env_file:
      - .env
    depends_on:
      - ppt_db

  ppt_db:
    image: mariadb:11.4.5
    container_name: ppt_db_container
    env_file:
      - .env
    volumes:
      - ppt_db_data:/var/lib/mariadb/data
    ports:
      - "3308:3306"
	
volumes:
  ppt_db_data: